'use strict';

'use strict';

var people = [
    {'Padme Amidala': 'An idealist during a time of corruption and war in the Republic, Padmé Amidala was determined to fix what wrongs she could in the Senate, where she represented her idyllic home planet of Naboo. Despite her busy career, Padmé found time for a secret, forbidden marriage with Anakin Skywalker, the Jedi hero of the Clone Wars. Though not a soldier, Padmé nonetheless found herself often in the thick of danger as she courageously defended her deepest held beliefs.'},
    {'Jar Jar Binks': 'A clumsy, well-meaning Gungan outcast on Naboo, Jar Jar Binks struggled to prove his worth throughout his life. Putting his awkward past behind him, Jar Jar left the swamps of Naboo to enter the even murkier waters of Coruscant politics, becoming a representative for his people in the galactic capital. There, his best intentions and eagerness to serve were exploited by scheming Senators and others in positions of power.'},
    {'C-3P0': 'Created with discarded scrap metal and parts by a young Anakin Skywalker on Tatooine, C-3PO was originally made to help Anakin\'s mother Shmi with household chores. Threepio would later meet his lifelong droid friend R2-D2 when Anakin befriended Padmé Amidala. Threepio and Artoo would pair up again for many adventures, although the protocol droid dreaded danger and would much rather focus on etiquette and diplomacy. Threepio would later serve useful as a translator for not only Padmé in negotiations during the Clone Wars, but also much later for other human companions Princess Leia and Luke Skywalker. The protocol droid\'s talent for communicating in other languages comes in handy when delegating with Jabba the Hutt, the Talz, and Ewoks.'},
    {'Lando Calrissian': 'Card player, gambler, scoundrel... Lando Calrissian preferred to operate outside the jurisdiction of the Empire. As administrator of Cloud City, a Tibanna gas mining facility hovering in the atmosphere of the planet Bespin, Lando welcomes his old friend Han Solo along with Leia, Chewbacca, Artoo and Threepio after their harrowing escape from the Empire on Hoth. But not all was what it seemed -- Lando had in fact made a deal with Darth Vader to capture the unfortunate Captain Solo in exchange for the security of Cloud City and its people. It was a deal Calrissian was set up to lose.'},
    {'Chewbacca': 'An immense, fur covered hero of great strength and loyalty, Chewbacca the Wookiee was a well-known figure in both the underworld and in the Rebel Alliance. Born on Kashyyyk over two centuries before the Battle of Yavin, Chewbacca was a wise, sophisticated being with exceptional skills in starship piloting and repair. He is a gentle giant, with compassionate blue-eyes set within a furry face. If his friends are threatened, though, Chewbacca unleashes his strength in a furious rage.'},
    {'Cody': 'A natural and practical leader in the clone army, Cody was a good fit for General Kenobi, to whom he was particularly loyal. Cody\'s keen ability to strategize, combined with his fierce combat style in the heat of battle, earned him the respect of the Jedi, and of his fellow clones as well. He often worked with Captain Rex, with whom he became friends. Cody enjoyed a close relationship with Kenobi, often sharing a tension-busting joke with him during intense moments on the battlefield. When Darth Sidious gave Order 66, however, Cody\'s loyalty to Kenobi was eclipsed by his clone indoctrination, and he ordered his troops to fire on the Jedi.'},
    {'Cont Dooku': 'A former Jedi Knight who left the Order when he became disillusioned with the corruption in the Republic, Dooku is the public face of the Separatist Alliance leadership. Many see him as a charismatic politician, but he has in truth been corrupted to the dark side by Darth Sidious.'},
    {'Boba Fett': 'A faceless enforcer, Boba Fett\'s distinctive, customized Mandalorian armor strikes fear in the hearts of fugitives. He is a legendary bounty hunter, accepting warrants from both the Empire and the criminal underworld. He is all business, laconic, and deadly.'},
    {'Jango Fett': 'In the final years of the Republic, Jango Fett was regarded as the best bounty hunter in the galaxy. A proficient marksman and unarmed combatant, Fett was covered in a sleek armored suit that concealed his scarred face. His combat gear featured an arsenal of weaponry, including retractable wrist blades, a snare, dual blaster pistols and other more exotic tools of the trade.'},
    {'General Grievous': 'eneral Grievous is a brilliant military strategist who can\'t be bothered with compassion or mercy. His lightning strikes and effective battle planning made him infamous in the eyes of a frightened Republic. A twisted melding of flesh and metal, General Grievous\' body is a deadly weapon. Grievous\' living matter was encased within his precision-engineered artificial body; inside the hardened shell beat the heart of a remorseless killer. A pressurized gut-sack held his vital organs, while his skull-like mask contained his living eyes and brain. Each of his six-fingered arms could split in two, resulting in an array of four limbs, each armed with a lightsaber that he would take as a grim trophy of his victims. Grievous could spin these arms in a whirling storm of deadly light. For all his imposing image, Grievous is a coward at heart. Only with opponents he believes he can defeat does he enter into combat. His hacking cough and thirst for winning every battle at any cost made him Enemy Number One in the eyes of the Jedi Council.'},
    {'Nute Gunray': 'Neimoidians are known for their business skills, but Nute Gunray, Viceroy of the Trade Federation, was more cutthroat than most. It was Gunray who conspired with the Sith Lord Darth Sidious to launch the blockade and subsequent invasion of Naboo. Once the planet was under siege, Gunray attempted to force Queen Amidala to sign a treaty that would legitimize the occupation. Amidala escaped, and returned to infiltrate her own palace and blast through Gunray\'s protectors. At gunpoint, Amidala declared Gunray\'s occupation over.'},
    {'Jabba the Hutt': ' loathsome slug of a gangster, Jabba the Hutt was the preeminent kingpin of crime in the Outer Rim Territories. Basing his operations out of Tatooine, the Hutt had his pudgy fingers in a number of criminal activities -- slavery, gunrunning, spice-smuggling, extortion and more.'},
    {'Qui-Gong Jinn': 'A venerable if maverick Jedi Master, Qui-Gon Jinn was a student of the living Force. Unlike other Jedi Masters, who often lose themselves in the meditation of the unifying Force, Qui-Gon Jinn lived for the moment, espousing a philosophy of "feel, don\'t think -- use your instincts." Were it not for Qui-Gon\'s unruly views, he would have undoubtedly been on the Jedi Council.'},
    {'Obi-Wan Kenobi': 'Also known as the "Negotiator," Obi-Wan Kenobi kept a cool head in the thick of combat. Obi-Wan was never at a loss for a quick word of wisdom or humor. He served as a General in the Repulic\'s army, with Clone Commander Cody often at his side.'},
    {'Plo Koon': 'Level-headed and unflappably calm, Jedi Master Plo Koon is among the wisest in the Jedi Order. Deeply concerned for life of every form, Plo Koon is especially devoted to protecting the clones under his command. Master Plo shares a special bond with Ahsoka Tano for finding her as a baby.'},
    {'Duchess Satine Kryze': 'The leader of Mandalore during the Clone Wars, Duchess Satine of Kalevala was a controversial figure. She longed to move Mandalore beyond its violent past and instituted a government that valued pacifism. Though Mandalore did begin to rebuild under her guidance, the dark shadow of the Clone Wars made the Duchess\' goals difficult to achieve. Not wanting to be mired in galactic conflict, the Duchess declared her planet neutral. This isolation brought hardship to Mandalore, and gave the Death Watch -- a violent faction of Mandalorians -- opportunity to ally with the Separatists and target the Duchess for assassination.'},
    {'Darth Maul': 'Darth Maul began life as one of the Nightbrothers on Dathomir. Darth Sidious brutally trained his apprentice to be a weapon of the Sith as well as a scheming mastermind. A relentless and acrobatic warrior with an extremely dangerous double-ended lightsaber, Maul longed for revenge against the Jedi, to destroy the Order and restore power to the Sith. Defeated at the Battle of Naboo, Maul disappeared from the galaxy for over a decade before reemerging as a new threat during the Clone Wars.'},
    {'Savage Opress': 'Savage Opress was once a common Nightbrother whose fighting prowess impressed Asajj Ventress. Transformed into a monstrous warrior by Mother Talzin, Opress became Count Dooku\'s new assassin and secret Sith apprentice. His loyalty, however, remained to Talzin. The Nightsisters leader gave Savage a new quest: to find his brother, Darth Maul, who had somehow survived his apparent death and was living in exile in the Outer Rim.'},
    {'Princess Lea Organa': 'Separated from a mother she barely knew and a father she later counted among her worst enemies, Leia Organa is a princess who grew up enmeshed in the politics of her time. She accomplished much by a young age: a leader in the Rebel Alliance, a former member of the Imperial Senate, and a member of the Royal Family of Alderaan. She never desired the power that was thrust upon her, but so strong was her commitment to peace, freedom, and democracy that she was willing to accept the burdens and the risks that it took to accomplish her goals.'},
    {'Palpatine': 'Palpatine was the last chancellor of the Old Republic, and the mastermind behind the biggest power-grab in galactic history. Practicing forbidden Sith techniques under his alternate identity of Darth Sidious, Palpatine arranged for his public persona to deflect suspicion while receiving praise and political respect. In time he moved from a senator representing Naboo to the Republic\'s Supreme Chancellor, and used the power of his office to launch the Clone Wars. With Order 66 bringing about the end of the Jedi Order, Palpatine declared himself Emperor. This marked an end to his "kindly old man" charade with which he had fooled even the wisest members of the Jedi Council.'},
    {'R2-D2': 'A resourceful astromech droid, R2-D2 served Padmé Amidala, Anakin Skywalker and Luke Skywalker in turn, showing great bravery in rescuing his masters and their friends from many perils. A skilled starship mechanic and fighter pilot\'s assistant, he formed an unlikely but enduring friendship with the fussy protocol droid C-3PO.'},
    {'Darth Sidious': 'Darth Sidious is the name assumed by Palpatine when he became a Sith Lord. In time, the Sith identity became more real than Palpatine\'s public face. After the Clone Wars and his ascension to Emperor, Palpatine essentially lived as Sidious for the remainder of his life.'},
    {'Anakin Skywalker': 'The Jedi Order discovered Anakin Skywalker as a slave boy on Tatooine. He had the potential to be the most powerful Force-user ever, and perhaps was even the Chosen One of an ancient Jedi prophecy. Apprenticed to Obi-Wan Kenobi, Anakin was a headstrong and challenging Padawan learner. Despite the strict rules of the Jedi Code, he fell in love with and secretly married Senator Padmé Amidala.'},
    {'Luke Skywalker': 'Raised as a farmboy on the backwater desert world of Tatooine, Luke had no idea that he was the secret son of Anakin Skywalker, the Chosen One born to bring balance to the Force. After his stepparents were murdered by the Empire, he destroyed the Death Star and became the Rebellion\'s greatest hero.'},
    {'Han Solo': 'An outlaw smuggler with a heart of gold, Han Solo proved his heroism after he got mixed up with the Rebel Alliance in their fight against the Empire. Han and his co-pilot Chewbacca flew the freighter Millennium Falcon to help the Rebels destroy the Death Star, but when Jabba the Hutt placed a price on his head, he was frozen in a carbonite slab and hung in Jabba\'s palace. His friends, including Luke Skywalker, Princess Leia, and Lando Calrissian, rescued Han in time for him to lead the ground attack that led to a Rebel triumph in the Battle of Endor.'},
    {'Ahsoka Tano': 'During the Clone Wars, Ahsoka Tano was Anakin Skywalker\'s Padawan learner, his apprentice in the ways of the Force. The young Togruta girl was discovered by Master Plo Koon and raised in the Jedi Temple. She graduated to Padawan at an early age, in part, as an effort by Master Yoda to teach her new Master, Anakin Skywalker, a greater sense of responsibility. Ahsoka is eager -- almost overly so -- to prove herself worthy of her status as a Padawan, to make Anakin proud, and to become a Jedi Knight.'},
    {'Dath Vader': 'Once a Jedi Knight, Anakin Skywalker swore loyalty to Sith Lord Darth Sidious in order to gain the power of the dark side of the Force. Vader betrayed the Jedi Order and his Master, Obi-Wan Kenobi. With the rise of the Galactic Empire, Darth Vader became the Emperor\'s dark enforcer. He carried out the Emperor\'s will, and commanded legions of Imperial troops. Vader was tasked with discovering the secret headquarters of the Rebel Alliance, as well as chasing down the Rebels who destroyed the Empire\'s massive Death Star battle station.'},
    {'Asajj Ventress': 'An assassin trained in the ways of the dark side by Count Dooku, Asajj Ventress yearned to be considered a true Sith, but such status wasn\'t allowed under the Sith\'s Rule of Two. Ventress fought with twin sabers, and clashed with Obi-Wan Kenobi and Anakin Skywalker many times.'},
    {'Wicket W. Warric': 'Wicket W. Warrick was the brave young Ewok who willingly joined the Rebellion and aided in the battle against the Empire on the forest moon of Endor. Even before he encountered the Rebels, Wicket had devised methods for defeating the Imperial machines, plans which were implemented after the Ewok befriended Princess Leia and recruited his tribe to the Alliance\'s cause. During the Battle of Endor, Wicket fought valiantly alongside his new allies.'},
    {'Watto': 'Watto was a Toydarian junk dealer in Mos Espa who bought Shmi Skywalker and her son Anakin from Gardulla the Hutt. An inveterate gambler, he sponsored Anakin in several Podraces, but often bet against his own slave, who was talented but inexperienced.'},
    {'Mace Windu': 'A grim Jedi Master with an amethyst-bladed lightsaber, Mace Windu was the champion of the Jedi Order, with little tolerance for the failings of the Senate, the arguments of politicians or the opinions of rebellious Jedi.'},
    {'Yoda': 'The Grand Master of the Jedi Council, Yoda has trained Jedi for over 800 years. He is wise and powerful in the ways of the Force, though his small size causes many to underestimate him. Yoda prefers meditation and reflection, spending much time pondering the mysteries of the Force. In his long lifetime, he has witnessed the decay of the Galactic Republic, and saw the Jedi Order transform from peacekeepers to battlefield commanders in the Clone Wars. When he must, Yoda wields his lightsaber and becomes a whirling warrior of great speed and agility. A stern instructor, Yoda nonetheless has a mischievous sense of humor. With the rise of the Galactic Empire, Yoda fled into exile and awaited the arrival of a new Jedi student to rekindle a new hope in the galaxy.'}
];
